### PR TITLE
main.js-patch-1 | Fix for Error Code : 4000 ("No Client ID Specified")

### PR DESCRIPTION
**Pull request by Jayme098**
Fix for : {"code":4000,"message":"Error 0xfa0: No Client ID Specified"}

### CODE REVIEW

**Comment by FIERCEDINO080** [comment]
still doesnt fix the problem for me.

**Comment by Jayme098** [comment]
@FIERCEDINO080 Join the SP Support Discord server : https://discord.gg/js and I will assist you to ensure you're using the fix correctly.

Or contact me directly : Jayme#0001 👍

**Comment by FIERCEDINO080** [comment]
@Jayme098 joined, i have to wait 10 mins to join, if you wanna DM me im fiercedino080#9380

**Comment by FIERCEDINO080** [comment]
guys, do not try to replace certain parts of the script.
remove the entire main.js file and replace it with this one.
thaat seemed to work for me.
thanks!

**Pull request closed without merging**
